spring.application.name=companyms


server.port=8081

##configure H2 database
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update


#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/company
spring.datasource.username=rahul
spring.datasource.password=Rahul@123
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#for creating schema and tables
spring.jpa.hibernate.ddl-auto=update


#jpa configuration
# Enable SQL logging
spring.jpa.show-sql=true

# Format SQL
spring.jpa.properties.hibernate.format_sql=true
